import { PropertyProps} from "@/interfaces";

export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    name: "Villa Ocean Breeze",
    address: { state: "Seminyak", city: "Bali", country: "Indonesia" },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    description: "A stunning villa with ocean views, private pool, and spacious living areas.",
    price: 3200,
    reviews: [
      {
        name: "Alice Johnson",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        rating: 5,
        comment: "Absolutely loved our stay here! The pool was amazing and the view breathtaking.",
      },
      {
        name: "Mark Smith",
        avatar: "https://randomuser.me/api/portraits/men/35.jpg",
        rating: 4,
        comment: "Great location and clean rooms, but the wifi was a bit slow.",
      },
    ],
    offers: { bed: "3", shower: "3", occupants: "4-6" },
    image: "https://example.com/image1.jpg",
    discount: "",
  },
  {
    name: "Mountain Escape Chalet",
    address: { state: "Aspen", city: "Colorado", country: "USA" },
    rating: 4.7,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    description: "Cozy chalet nestled in the mountains with a warm fireplace and scenic views.",
    price: 1800,
    reviews: [
      {
        name: "Linda Green",
        avatar: "https://randomuser.me/api/portraits/women/50.jpg",
        rating: 5,
        comment: "Perfect getaway for winter! Loved the fireplace and mountain views.",
      },
      {
        name: "James Lee",
        avatar: "https://randomuser.me/api/portraits/men/22.jpg",
        rating: 4,
        comment: "Nice place but parking was limited.",
      },
    ],
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: "https://example.com/image2.jpg",
    discount: "30",
  },
  {
    name: "Cozy Desert Retreat",
    address: { state: "Palm Springs", city: "California", country: "USA" },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    description: "Quiet desert home with pet-friendly policies and easy self-checkin.",
    price: 1500,
    reviews: [
      {
        name: "Rachel Adams",
        avatar: "https://randomuser.me/api/portraits/women/30.jpg",
        rating: 5,
        comment: "Peaceful and cozy, perfect for a relaxing weekend.",
      },
      {
        name: "Tom Brown",
        avatar: "https://randomuser.me/api/portraits/men/41.jpg",
        rating: 4,
        comment: "Nice location but could use more kitchen utensils.",
      },
    ],
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: "https://example.com/image3.jpg",
    discount: "",
  },
  {
    name: "City Lights Penthouse",
    address: { state: "New York", city: "New York", country: "USA" },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    description: "Modern penthouse with spectacular city views and 24-hour check-in.",
    price: 4500,
    reviews: [
      {
        name: "Samantha Carter",
        avatar: "https://randomuser.me/api/portraits/women/52.jpg",
        rating: 5,
        comment: "Amazing view and very convenient location downtown!",
      },
      {
        name: "Daniel Wright",
        avatar: "https://randomuser.me/api/portraits/men/29.jpg",
        rating: 4,
        comment: "Comfortable and stylish but a bit noisy at night.",
      },
    ],
    offers: { bed: "2", shower: "2", occupants: "2-4" },
    image: "https://example.com/image4.jpg",
    discount: "15",
  },
  {
    name: "Riverside Cabin",
    address: { state: "Queenstown", city: "Otago", country: "New Zealand" },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    description: "Relaxing cabin by the river with private dock and free kayak use.",
    price: 2800,
    reviews: [
      {
        name: "Laura Mitchell",
        avatar: "https://randomuser.me/api/portraits/women/27.jpg",
        rating: 5,
        comment: "The private dock was a highlight, beautiful and peaceful setting.",
      },
      {
        name: "Peter Thompson",
        avatar: "https://randomuser.me/api/portraits/men/40.jpg",
        rating: 4,
        comment: "Great stay, but the kitchen appliances were outdated.",
      },
    ],
    offers: { bed: "3", shower: "2", occupants: "4-6" },
    image: "https://example.com/image5.jpg",
    discount: "20",
  },
  {
    name: "Modern Beachfront Villa",
    address: { state: "Sidemen", city: "Bali", country: "Indonesia" },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    description: "Luxurious beachfront villa with private pool and chef services.",
    price: 5000,
    reviews: [
      {
        name: "Monica Bell",
        avatar: "https://randomuser.me/api/portraits/women/24.jpg",
        rating: 5,
        comment: "Unforgettable experience, excellent chef and beautiful villa.",
      },
      {
        name: "Eric Johnson",
        avatar: "https://randomuser.me/api/portraits/men/33.jpg",
        rating: 5,
        comment: "Perfect for family vacations with lots of space and amenities.",
      },
    ],
    offers: { bed: "5", shower: "4", occupants: "8-10" },
    image: "https://example.com/image6.jpg",
    discount: "",
  },
  {
    name: "Lakeside Chalet",
    address: { state: "Banff", city: "Alberta", country: "Canada" },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    description: "Cozy chalet by the lake with mountain views and nearby hiking trails.",
    price: 2300,
    reviews: [
      {
        name: "Kevin White",
        avatar: "https://randomuser.me/api/portraits/men/45.jpg",
        rating: 4,
        comment: "Beautiful location, peaceful surroundings, good for hiking lovers.",
      },
      {
        name: "Sara Collins",
        avatar: "https://randomuser.me/api/portraits/women/37.jpg",
        rating: 3,
        comment: "Nice chalet but heating was insufficient on cold nights.",
      },
    ],
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "https://example.com/image7.jpg",
    discount: "10",
  },
  {
    name: "Tropical Garden Villa",
    address: { state: "Koh Samui", city: "Surat Thani", country: "Thailand" },
    rating: 4.8,
    category: ["Garden", "Free Parking", "Self Checkin"],
    description: "Beautiful villa surrounded by lush tropical gardens with free parking.",
    price: 2750,
    reviews: [
      {
        name: "Nina Lopez",
        avatar: "https://randomuser.me/api/portraits/women/41.jpg",
        rating: 5,
        comment: "A peaceful oasis in the middle of the city, perfect for relaxing.",
      },
      {
        name: "Jack Evans",
        avatar: "https://randomuser.me/api/portraits/men/48.jpg",
        rating: 4,
        comment: "Lovely garden, convenient parking, easy check-in process.",
      },
    ],
    offers: { bed: "3", shower: "3", occupants: "5-6" },
    image: "https://example.com/image8.jpg",
    discount: "25",
  },
  {
    name: "Urban Loft",
    address: { state: "Berlin", city: "Berlin", country: "Germany" },
    rating: 4.6,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    description: "Modern loft apartment located in the city center with fast wifi.",
    price: 2000,
    reviews: [
      {
        name: "Emma Fisher",
        avatar: "https://randomuser.me/api/portraits/women/29.jpg",
        rating: 4,
        comment: "Great location and clean space, perfect for city trips.",
      },
      {
        name: "Liam Wilson",
        avatar: "https://randomuser.me/api/portraits/men/31.jpg",
        rating: 3,
        comment: "Wifi was a bit unreliable at times.",
      },
    ],
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: "https://example.com/image9.jpg",
    discount: "",
  },
  {
    name: "Secluded Forest Cabin",
    address: { state: "Whistler", city: "British Columbia", country: "Canada" },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    description: "Private cabin in the forest with hot tub and self-checkin.",
    price: 2600,
    reviews: [
      {
        name: "Olivia Martinez",
        avatar: "https://randomuser.me/api/portraits/women/35.jpg",
        rating: 5,
        comment: "A serene escape with a fantastic hot tub!",
      },
      {
        name: "Ethan Scott",
        avatar: "https://randomuser.me/api/portraits/men/40.jpg",
        rating: 4,
        comment: "Very peaceful but the roads to the cabin are rough.",
      },
    ],
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: "https://example.com/image10.jpg",
    discount: "40",
  },
  {
    name: "Cliffside Villa",
    address: { state: "Amalfi", city: "Salerno", country: "Italy" },
    rating: 4.93,
    category: ["Cliffside", "Infinity Pool", "Sea View"],
    description: "Luxury villa on the cliff with infinity pool and panoramic sea views.",
    price: 6000,
    reviews: [
      {
        name: "Isabella Russo",
        avatar: "https://randomuser.me/api/portraits/women/39.jpg",
        rating: 5,
        comment: "Breathtaking views and superb infinity pool. Truly unforgettable stay.",
      },
      {
        name: "Marco Bianchi",
        avatar: "https://randomuser.me/api/portraits/men/42.jpg",
        rating: 5,
        comment: "Excellent service and location. Highly recommend!",
      },
    ],
    offers: { bed: "4", shower: "4", occupants: "6-8" },
    image: "https://example.com/image11.jpg",
    discount: "50",
  },
  {
    name: "Coastal Escape Villa",
    address: { state: "Noosa", city: "Queensland", country: "Australia" },
    rating: 4.83,
    category: ["Beachfront", "Pet Friendly", "Free Parking"],
    description: "Charming beachfront villa with pet-friendly policy and free parking.",
    price: 3400,
    reviews: [
      {
        name: "Zoe Mitchell",
        avatar: "https://randomuser.me/api/portraits/women/28.jpg",
        rating: 5,
        comment: "Loved the beach access and pet-friendly environment.",
      },
      {
        name: "Ryan Clark",
        avatar: "https://randomuser.me/api/portraits/men/37.jpg",
        rating: 4,
        comment: "Great location, but kitchen equipment could be improved.",
      },
    ],
    offers: { bed: "3", shower: "3", occupants: "4-6" },
    image: "https://example.com/image12.jpg",
    discount: "",
  },
  {
    name: "Historical Villa",
    address: { state: "Florence", city: "Tuscany", country: "Italy" },
    rating: 4.67,
    category: ["Historical", "Free Breakfast", "Self Checkin"],
    description: "Villa rich with history, including free breakfast and easy check-in.",
    price: 2700,
    reviews: [
      {
        name: "Giulia Conti",
        avatar: "https://randomuser.me/api/portraits/women/33.jpg",
        rating: 5,
        comment: "Amazing historical architecture and delicious breakfast!",
      },
      {
        name: "Luca Romano",
        avatar: "https://randomuser.me/api/portraits/men/30.jpg",
        rating: 4,
        comment: "Loved the vibe, but parking was a bit challenging.",
      },
    ],
    offers: { bed: "2", shower: "2", occupants: "2-4" },
    image: "https://example.com/image13.jpg",
    discount: "35",
  },
  {
    name: "Downtown Apartment",
    address: { state: "Tokyo", city: "Tokyo", country: "Japan" },
    rating: 4.81,
    category: ["City Center", "Free WiFi", "Public Transport"],
    description: "Convenient apartment in downtown Tokyo with fast WiFi and transport access.",
    price: 2200,
    reviews: [
      {
        name: "Yuki Tanaka",
        avatar: "https://randomuser.me/api/portraits/women/22.jpg",
        rating: 5,
        comment: "Great location for exploring the city, super convenient.",
      },
      {
        name: "Kenji Sato",
        avatar: "https://randomuser.me/api/portraits/men/25.jpg",
        rating: 4,
        comment: "Comfortable stay but the apartment was a bit small.",
      },
    ],
    offers: { bed: "1", shower: "1", occupants: "2" },
    image: "https://example.com/image14.jpg",
    discount: "",
  },
  {
    name: "Luxury Safari Lodge",
    address: { state: "Serengeti", city: "Mara", country: "Tanzania" },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    description: "Exclusive safari lodge with guided tours and complimentary breakfast.",
    price: 4500,
    reviews: [
      {
        name: "David Brown",
        avatar: "https://randomuser.me/api/portraits/men/44.jpg",
        rating: 5,
        comment: "Amazing safari experience and wonderful lodge facilities.",
      },
      {
        name: "Angela White",
        avatar: "https://randomuser.me/api/portraits/women/47.jpg",
        rating: 5,
        comment: "Fantastic tours and very comfortable accommodations.",
      },
    ],
    offers: { bed: "4", shower: "4", occupants: "6-8" },
    image: "https://example.com/image15.jpg",
    discount: "20",
  },
  {
    name: "Countryside Cottage",
    address: { state: "Cotswolds", city: "Gloucestershire", country: "UK" },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Checkin"],
    description: "Charming cottage in the countryside with cozy fireplace and self check-in.",
    price: 1800,
    reviews: [
      {
        name: "Emma Thompson",
        avatar: "https://randomuser.me/api/portraits/women/49.jpg",
        rating: 4,
        comment: "Cozy and peaceful, loved the fireplace.",
      },
      {
        name: "Oliver Scott",
        avatar: "https://randomuser.me/api/portraits/men/46.jpg",
        rating: 3,
        comment: "Nice spot but a bit remote for quick shopping.",
      },
    ],
    offers: { bed: "2", shower: "1", occupants: "2-4" },
    image: "https://example.com/image16.jpg",
    discount: "25",
  },
  {
    name: "Riverfront Mansion",
    address: { state: "Paris", city: "Île-de-France", country: "France" },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Checkin"],
    description: "Elegant mansion on the riverfront with private garden and self check-in.",
    price: 5000,
    reviews: [
      {
        name: "Sophie Dubois",
        avatar: "https://randomuser.me/api/portraits/women/38.jpg",
        rating: 5,
        comment: "Beautiful property, perfect for a luxurious stay in Paris.",
      },
      {
        name: "Jean Martin",
        avatar: "https://randomuser.me/api/portraits/men/39.jpg",
        rating: 4,
        comment: "Great mansion but a bit pricey.",
      },
    ],
    offers: { bed: "4", shower: "3", occupants: "6-8" },
    image: "https://example.com/image17.jpg",
    discount: "30",
  },
  {
    name: "Ski Chalet",
    address: { state: "Zermatt", city: "Valais", country: "Switzerland" },
    rating: 4.75,
    category: ["Mountain View", "Ski Access", "Fireplace"],
    description: "Chalet with easy ski access, mountain views and cozy fireplace.",
    price: 3900,
    reviews: [
      {
        name: "Hans Meier",
        avatar: "https://randomuser.me/api/portraits/men/40.jpg",
        rating: 5,
        comment: "Perfect for ski lovers, very comfortable and warm.",
      },
      {
        name: "Anna Keller",
        avatar: "https://randomuser.me/api/portraits/women/34.jpg",
        rating: 4,
        comment: "Great location but kitchen was small.",
      },
    ],
    offers: { bed: "3", shower: "2", occupants: "4-5" },
    image: "https://example.com/image18.jpg",
    discount: "",
  },
  {
    name: "Island Paradise Villa",
    address: { state: "Maui", city: "Hawaii", country: "USA" },
    rating: 4.9,
    category: ["Island", "Beach Access", "Private Pool"],
    description: "Tropical villa with private pool and direct beach access.",
    price: 5500,
    reviews: [
      {
        name: "Mia Anderson",
        avatar: "https://randomuser.me/api/portraits/women/45.jpg",
        rating: 5,
        comment: "A paradise indeed, fantastic pool and beach access.",
      },
      {
        name: "Noah Davis",
        avatar: "https://randomuser.me/api/portraits/men/38.jpg",
        rating: 5,
        comment: "Excellent amenities and beautiful surroundings.",
      },
    ],
    offers: { bed: "4", shower: "4", occupants: "6-8" },
    image: "https://example.com/image19.jpg",
    discount: "15",
  },
  {
    name: "Urban Studio",
    address: { state: "London", city: "Greater London", country: "UK" },
    rating: 4.55,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    description: "Compact studio apartment in central London with free wifi.",
    price: 1700,
    reviews: [
      {
        name: "Charlotte Green",
        avatar: "https://randomuser.me/api/portraits/women/31.jpg",
        rating: 4,
        comment: "Good location and clean, but small for longer stays.",
      },
      {
        name: "Harry Walker",
        avatar: "https://randomuser.me/api/portraits/men/34.jpg",
        rating: 3,
        comment: "Wifi could be better, otherwise fine.",
      },
    ],
    offers: { bed: "1", shower: "1", occupants: "1-2" },
    image: "https://example.com/image20.jpg",
    discount: "",
  },
];
